Fix errors on dart2js compilation by useing ternary operator instead of null aware operator.
An original error message:
	Error: Expected a declaration, but got ';'.
      		: headers = headers ?? {};